import random
import discord


def generate_loot(number_of_items, encounter_rank):
    # Define possible loot items
    common_loot_table = [
        'Potion of climbing',
        'Potion of healing',
        'Spell scroll (1st level)',
        'Spell scroll (cantrip)'
    ]

    uncommon_loot_table = [
        'Adamantine armor',
        'Alchemy jug',
        'Ammunition +1',
        'Amulet of proof against',
        'detection and location',
        'Bag of holding',
        'Bag of tricks',
        'Boots of elvenkind',
        'Boots of striding and springing',
        'Boots of the winterlands',
        'Bracers of archery',
        'Brooch of shielding',
        'Broom of flying',
        'Cap of water breathing',
        'Circlet of blasting',
        'Cloak of elvenkind',
        'Cloak of protection',
        'Cloak of the manta ray',
        'Decanter of endless water',
        'Deck of illusions',
        'Driftglobe',
        'Dust of disappearance',
        'Dust of dryness',
        'Dust of sneezing and choking',
        'Elemental gem',
        'Eversmoking bottle',
        'Eyes of charming',
        'Eyes of minute seeing',
        'Eyes of the eagle',
        'Figurine of wondrous power (silver raven)',
        'Gauntlets of ogre power',
        'Gem of brightness',
        'Gloves of missile snaring',
        'Gloves of swimming and climbing',
        'Gloves of thievery',
        'Goggles of night',
        'Hat of disguise',
        'Headband of intellect',
        'Helm of comprehending languages',
        'Helm of telepathy',
        'Immovable rod',
        'Instrument of the bard (Doss lute)',
        'Instrument of the bard (Fochlucan bandore)',
        'Instrument of the bard (Mac-Fuirmidh cittern)',
        'Javelin of lightning',
        'Keoghtom’s ointment',
        'Lantern of revealing',
        'Mariner’s armor',
        'Medallion of thoughts',
        'Mithral armor',
        'Necklace of adaptation',
        'Oil of slipperiness',
        'Pearl of power',
        'Periapt of health',
        'Periapt of wound closure',
        'Philter of love',
        'Pipes of haunting',
        'Pipes of the sewers',
        'Potion of animal friendship',
        'Potion of fire breath',
        'Potion of giant strength (hill giant)',
        'Potion of greater healing',
        'Potion of growth',
        'Potion of poison',
        'Potion of resistance',
        'Potion of water breathing',
        'Quiver of Ehlonna',
        'Ring of jumping',
        'Ring of mind shielding',
        'Ring of swimming',
        'Ring of warmth',
        'Ring of water walking',
        'Robe of useful items',
        'Rod of the pact keeper +1',
        'Rope of climbing',
        'Saddle of the cavalier',
        'Sending stones',
        'Sentinel shield',
        'Shield +1',
        'Slippers of spider climbing',
        'Spell scroll (2nd level)',
        'Spell scroll (3rd level)',
        'Staff of the adder',
        'Staff of the python',
        'Stone of good luck (luckstone)',
        'Sword of vengeance',
        'Trident of fish command',
        'Wand of magic detection',
        'Wand of magic missiles',
        'Wand of secrets',
        'Wand of the war mage +1',
        'Wand of web',
        'Weapon +1',
        'Weapon of warning',
        'Wind fan',
        'Winged boots'
    ]

    rare_loot_table = [
        'Ammunition +2',
        'Amulet of health',
        'Armor +1',
        'Armor of resistance',
        'Armor of vulnerability',
        'Arrow-catching shield',
        'Bag of beans',
        'Bead of force',
        'Belt of dwarvenkind',
        'Belt of giant strength (hill giant)',
        'Berserker axe',
        'Boots of levitation',
        'Boots of speed',
        'Bowl of commanding water elementals',
        'Bracers of defense',
        'Brazier of commanding fire elementals',
        'Cape of the mountebank',
        'Censer of controlling air elementals',
        'Chime of opening',
        'Cloak of displacement',
        'Cloak of the bat',
        'Cube of force',
        'Daern’s instant fortress',
        'Dagger of venom',
        'Dimensional shackles',
        'Dragon slayer',
        'Elixir of health',
        'Elven chain',
        'Figurine of wondrous power (bronze griffon)',
        'Figurine of wondrous power (ebony fly)',
        'Figurine of wondrous power (golden lions)',
        'Figurine of wondrous power (ivory goats)',
        'Figurine of wondrous power (marble elephant)',
        'Figurine of wondrous power (onyx dog)',
        'Figurine of wondrous power (serpentine owl)',
        'Flame tongue',
        'Folding boat',
        'Gem of seeing',
        'Giant slayer',
        'Glamoured studded leather',
        'Helm of teleportation',
        'Heward’s handy haversack',
        'Horn of blasting',
        'Horn of valhalla (silver or brass)',
        'Horseshoes of speed',
        'Instrument of the bard (Canaith mandolin)',
        'Instrument of the bard (Cli lyre)',
        'Ioun stone (awareness)',
        'Ioun stone (protection)',
        'Ioun stone (reserve)',
        'Ioun stone (sustenance)',
        'Iron bands of bilarro',
        'Mace of disruption',
        'Mace of smiting',
        'Mace of terror',
        'Mantle of spell resistance',
        'Necklace of fireballs',
        'Necklace of prayer beads',
        'Oil of etherealness',
        'Periapt of proof against poison',
        'Portable hole',
        'Potion of clairvoyance',
        'Potion of diminution',
        'Potion of gaseous form',
        'Potion of giant strength (fire giant)',
        'Potion of giant strength',
        '(frost or stone giant)',
        'Potion of heroism',
        'Potion of invulnerability',
        'Potion of mind reading',
        'Potion of superior healing',
        'Quaal’s feather token',
        'Ring of animal influence',
        'Ring of evasion',
        'Ring of feather falling',
        'Ring of free action',
        'Ring of protection',
        'Ring of resistance',
        'Ring of spell storing',
        'Ring of the ram',
        'Ring of x-ray vision',
        'Robe of eyes',
        'Rod of rulership',
        'Rod of the pact keeper +2',
        'Rope of entanglement',
        'Scroll of protection',
        'Shield +2',
        'Shield of missile attraction',
        'Spell scroll (4th level)',
        'Spell scroll (5th level)',
        'Staff of charming',
        'Staff of healing',
        'Staff of swarming insects',
        'Staff of the woodlands',
        'Staff of withering',
        'Stone of controlling earth elementals',
        'Sun blade',
        'Sword of life stealing',
        'Sword of wounding',
        'Tentacle rod',
        'Vicious weapon',
        'Wand of binding',
        'Wand of enemy detection',
        'Wand of fear',
        'Wand of fireballs',
        'Wand of lightning bolts',
        'Wand of paralysis',
        'Wand of the war mage +2',
        'Wand of wonder',
        'Weapon +2',
        'Wings of flying'
    ]

    very_rare_loot_table = [
        'Ammunition +3',
        'Amulet of the planes',
        'Animated shield',
        'Armor +2',
        'Arrow of slaying',
        'Bag of devouring',
        'Belt of giant strength (fire giant)',
        'Belt of giant strength (frost or stone giant)',
        'Candle of invocation',
        'Carpet of flying',
        'Cloak of arachnida',
        'Crystal ball',
        'Dancing sword',
        'Demon armor',
        'Dragon scale mail',
        'Dwarven plate',
        'Dwarven thrower',
        'Efreeti bottle',
        'Figurine of wondrous power (obsidian steed)',
        'Frost brand',
        'Helm of brilliance',
        'Horn of valhalla (bronze)',
        'Horseshoes of a zephyr',
        'Instrument of the bard (Anstruth harp)',
        'Ioun stone (absorption)',
        'Ioun stone (agility)',
        'Ioun stone (fortitude)',
        'Ioun stone (insight)',
        'Ioun stone (intellect)',
        'Ioun stone (leadership)',
        'Ioun stone (strength)',
        'Manual of bodily health',
        'Manual of gainful exercise',
        'Manual of golems',
        'Manual of quickness of action',
        'Mirror of life trapping',
        'Nine lives stealer',
        'Nolzur’s marvelous pigments',
        'Oathbow',
        'Oil of sharpness',
        'Potion of flying',
        'Potion of giant strength (cloud giant)',
        'Potion of invisibility',
        'Potion of longevity',
        'Potion of speed',
        'Potion of supreme healing',
        'Potion of vitality',
        'Ring of regeneration',
        'Ring of shooting stars',
        'Ring of telekinesis',
        'Robe of scintillating colors',
        'Robe of stars',
        'Rod of absorption',
        'Rod of alertness',
        'Rod of security',
        'Rod of the pact keeper +3',
        'Scimitar of speed',
        'Shield +3',
        'Spell scroll (6th level)',
        'Spell scroll (7th level)',
        'Spell scroll (8th level)',
        'Spellguard shield',
        'Staff of fire',
        'Staff of frost',
        'Staff of power',
        'Staff of striking',
        'Staff of thunder and lightning',
        'Sword of sharpness',
        'Tome of clear thought',
        'Tome of leadership and influence',
        'Tome of understanding',
        'Wand of polymorph',
        'Wand of the war mage +3',
        'Weapon +3'
    ]

    legendary_loot_table = [
        'Apparatus of Kwalish',
        'Armor +3',
        'Armor of invulnerability',
        'Belt of giant strength (cloud giant)',
        'Belt of giant strength (storm giant)',
        'Blackrazor',
        'Cloak of invisibility',
        'Crystal ball',
        'Cubic gate',
        'Deck of many things',
        'Defender',
        'Efreeti chain',
        'Hammer of thunderbolts',
        'Holy avenger',
        'Horn of valhalla (iron)',
        'Instrument of the bard (Ollamh harp)',
        'Ioun stone (greater absorption)',
        'Ioun stone (mastery)',
        'Ioun stone (regeneration)',
        'Iron flask',
        'Luck blade',
        'Moonblade',
        'Plate armor of etherealness',
        'Potion of giant strength (storm giant)',
        'Ring of djinni summoning',
        'Ring of elemental command',
        'Ring of invisibility',
        'Ring of spell turning',
        'Ring of three wishes',
        'Robe of the archmagi',
        'Rod of lordly might',
        'Rod of resurrection',
        'Scarab of protection',
        'Sovereign glue',
        'Spell scroll (9th level)',
        'Sphere of annihilation',
        'Staff of the magi',
        'Sword of answering',
        'Talisman of pure good',
        'Talisman of the sphere',
        'Talisman of ultimate evil',
        'Tome of the stilled tongue',
        'Universal solvent',
        'Vorpal sword',
        'Wave',
        'Well of many worlds'
        'Whelm'
    ]

    weighted_rank_table = {
        1: [(common_loot_table, 0.6), (uncommon_loot_table, 0.4)],
        2: [(common_loot_table, 0.5), (uncommon_loot_table, 0.45), (rare_loot_table, 0.05)],
        3: [(common_loot_table, 0.4), (uncommon_loot_table, 0.5), (rare_loot_table, 0.1)],
        4: [(common_loot_table, 0.25), (uncommon_loot_table, 0.55), (rare_loot_table, 0.15),
            (very_rare_loot_table, 0.05)],
        5: [(uncommon_loot_table, 0.7), (rare_loot_table, 0.20), (very_rare_loot_table, 0.1)],
        6: [(uncommon_loot_table, 0.5), (rare_loot_table, 0.3), (very_rare_loot_table, 0.15),
            (legendary_loot_table, 0.05)]
    }

    chosen_rank_weight = weighted_rank_table.get(encounter_rank)

    chosen_tables = [t for t, w in chosen_rank_weight]
    weights = [w for t, w in chosen_rank_weight]

    # Randomly select an item from the loot table
    chosen_items = []

    embed = discord.Embed(
        title="Collect your prize",
        description="Items looted from the slain bodies of your enemies",
        color=discord.Color.dark_red())

    for _ in range(number_of_items):
        selected_sub_table_index_and_item = random.choices(list(enumerate(chosen_tables)),
                                                           weights=weights,
                                                           k=1)[0]
        selected_sub_table_index, selected_sub_table = selected_sub_table_index_and_item

        selected_item_original_name = random.choice(selected_sub_table)

        # Attach a message indicating which table it came from
        rarity_message = ""
        if selected_sub_table is common_loot_table:
            rarity_message = "Common"
        elif selected_sub_table is uncommon_loot_table:
            rarity_message = "UnCommon"
        elif selected_sub_table is rare_loot_table:
            rarity_message = "Rare"
        elif selected_sub_table is very_rare_loot_table:
            rarity_message = "Very Rare"
        elif selected_sub_table is legendary_loot_table:
            rarity_message = "Legendary"

        selected_item_with_message = f"\n-{selected_item_original_name} ({rarity_message})"

        embed.add_field(name=f"{selected_item_original_name}", value=f"{rarity_message}", inline=False)

        chosen_items.append(selected_item_with_message)

    return embed
